# Generated by Django 5.1.7 on 2025-03-09 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('ctc', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('batch', models.IntegerField(default=2021)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('EP', 'Engineering Physics'), ('EE', 'Electrical Engineering'), ('MNC', 'Mathematics & Computing'), ('MMAE', 'Mechanical & Manufacturing Engineering'), ('CIVIL', 'Civil Engineering'), ('CHEMICAL', 'Chemical Engineering')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('selected', models.BooleanField(default=False)),
                ('placementid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.placement')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'unique_together': {('studentid', 'placementid')},
            },
        ),
    ]
